# Generated by Django 2.1.5 on 2019-02-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pesan', models.TextField(max_length=1024)),
                ('profilePict', models.ImageField(upload_to='img')),
                ('wokingExp', models.TextField(max_length=100)),
                ('jobPosition', models.CharField(max_length=100)),
            ],
        ),
    ]
