# Generated by Django 2.1.5 on 2019-02-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorbase',
            name='profilePict',
            field=models.ImageField(upload_to='mentor'),
        ),
    ]
