# Generated by Django 2.1.5 on 2019-02-12 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isi', models.CharField(max_length=255)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('jumlahComment', models.TextField(max_length=255)),
                ('gambar', models.ImageField(upload_to='img')),
            ],
        ),
    ]
