# Generated by Django 2.1.5 on 2019-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20190212_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='jumlahComment',
            field=models.CharField(max_length=100),
        ),
    ]
