# Generated by Django 2.1.5 on 2019-02-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20190212_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='linkComment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
