# Generated by Django 2.1.5 on 2019-02-13 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_artikel_linkcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
