# Generated by Django 2.1.5 on 2019-02-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mentee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteebase',
            name='jobPosition',
        ),
        migrations.RemoveField(
            model_name='menteebase',
            name='wokingExp',
        ),
    ]
